# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    container_name: music-container
    image: postgres:14.1-alpine  
    command: ['postgres', '-c', 'log_statement=all']
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 1234 
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_user.sql
    restart: always